main: Main
name: TribulaTemplate #TODO
version: 1.0
author: Technocoder
description: Tribula Template #TODO
commands:
   templatecmd: #TODO
      description: This is a demo command. #TODO
      usage: /<command>