main: io.github.techno_brony.tribula.mobs.Main
name: TribulaMobs #TODO
version: 1.0
author: TechnoBrony
description: Tribula Mobs #TODO
commands:
   templatecmd: #TODO
      description: This is a demo command. #TODO
      usage: /<command>