main: Main
name: TribulaMobs #TODO
version: 1.0
author: Technocoder
description: Tribula Mobs #TODO
commands:
   templatecmd: #TODO
      description: This is a demo command. #TODO
      usage: /<command>